[asyn_logger]
# 0 only_terminal ,  1 only_file , 2 both of them , other will be 0
output_mode = 2
# 0 info , 1 warn , 2 debug , other will be 0
log_mode = 0

# cloud service(0 close)
open_oss = 0
open_cos = 0

# file
# 0 storage by day , 1 storage by size(m)
file_storage_mode = 0
file_size = 100
file_path = "./.logs"


[aliyun_oss]
# aliyunOSS config
oss_endpoint = ""
oss_accessKeyId = ""
oss_accessKeySecret = ""
oss_bucketName = ""

